### ISSUE TITLE
arguments not forwarded

### ISSUE THREAD

**Issue by extrawurst** [elliotchance/redismock#10]
Great library @elliotchance !

I was wondering why arguments are not forwarded in `cmdable.go`? 

I wanted to write expected calls to even match the arguments to make sure everything is forwared to redis correctly and then realized that all `m.Called()` lines do not forward the arguments. Is that intended?

**Comment by elliotchance** [comment]
This bug was previously raised in #9. Hopefully, @nmakro will get some time to work on it soon.

**Comment by extrawurst** [comment]
To be honest, I figured it's much easier to have the mock for redis be auto generated since I don't need the bridge to miniredis anyway and `mockgen` is doing exactly that: https://github.com/golang/mock

**Comment by elliotchance** [comment]
Ah yes, that works as well! :)

**Comment by elliotchance** [comment]
@Extrawurst, I had to think about it for a minute; why I created this library, and not just use another mocking framework. I use this when I want to have a persistent redis behind it, but dynamically control some behaviour during a particular test. Such as a timeout or connection difficulty.
