### ISSUE TITLE
Add LPOS command support

### ISSUE THREAD

**Issue by tommyalatalo** [elliotchance/redismock#28]
Redis 6.0.6 added support for a new LPOS command to find index of a key in a list.
Opened pull request #27 to add this command to fulfill Cmdable interface.

Should the command be added to v6 and v7 as well? (I'm a new redis user, so I don't know the history and significance of the api versions)

**Comment by elliotchance** [comment]
I have merged your fix, thank you. Having it only in v8 is fine. If anyone can only use a v6 or v7 and needs that LPos then it can be added by them.
